language: python
dist: xenial
sudo: required

python:
  - "2.7.14"

addons:
  postgresql: "9.5"
  apt:
    packages:
    - libpq5=9.5.13-0ubuntu0.16.04
    - libpq-dev=9.5.13-0ubuntu0.16.04

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - export NPM_CONFIG_PREFIX=./node_modules

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - npm install karma
  - npm install karma-browserstack-launcher --save-dev

script:
  - python charts/manage.py test
  - coverage run charts/manage.py test

after_success: coveralls

notifications:
  slack: lacnic-eng:jSDKPP0pyOgA5JV4lsQTGtuP
