language: python
sudo: required

python:
  - "2.7"

services:
  - postgresql

  apt:
    packages:
    - libpq-dev
    - python-dev
    - python-psycopg2

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - export NPM_CONFIG_PREFIX=./node_modules

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - npm install karma
  - npm install karma-browserstack-launcher --save-dev
  - npm install --save -g artillery

script:
  - python charts/manage.py test
  - coverage run charts/manage.py test

after_success: coveralls

notifications:
  slack: lacnic-eng:jSDKPP0pyOgA5JV4lsQTGtuP
