language: python
sudo: required

python:
  - "2.7"

services:
  - postgresql

addons:
#  code_climate:
#    repo_token: f7fa84853f7688638c4692deda36f9c85b4c4099fd42da5a6e7097c2f29cd651
  apt:
    packages:
    - libpq-dev
    - python-dev
    - python-psycopg2

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - export NPM_CONFIG_PREFIX=./node_modules

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
#  - mv simon-web/simon_project/passwords_dummy.py simon-web/simon_project/passwords.py
#  - psql -c 'create database monitor;' -U postgres
#  - python monitor/manage.py makemigrations 
#  - python monitor/manage.py migrate 
#  - python monitor/manage.py makemigrations app 
#  - python monitor/manage.py migrate app
  - npm install -g n
  - npm install karma
  - npm install karma-browserstack-launcher --save-dev
  - npm install --save -g artillery

script:
  - python charts/manage.py test
  - coverage run charts/manage.py test
  - n stable
  - artillery run artillery.yml
#  - simon-javascript/node_modules/karma/bin/karma start simon-javascript/my.conf.js --single-run

after_success: coveralls

notifications:
  slack: lacnic-eng:jSDKPP0pyOgA5JV4lsQTGtuP
